const db = require('../config/db');  // This controller links the Multer file path to the MySQL metadata (Title, Description, Category)

exports.uploadMaterial = async (req, res) => {
    try {
        const { title, description, category } = req.body;
        const uploader_id = req.user.id; // Automatically pulled from the JWT token
        const file_url = req.file.path;  // The path generated by Multer

        // Requirement: Default status is 'pending' for Admin Moderation [cite: 18, 40]
        const sql = `
            INSERT INTO materials (title, description, file_url, category, uploader_id) 
            VALUES (?, ?, ?, ?, ?)
        `;

        await db.query(sql, [title, description, file_url, category, uploader_id]);

        res.status(201).json({
            message: "Success! Material uploaded and saved to database.",
            details: { title, category, file_url }
        });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};